### ISSUE TITLE
How to make button fill entire height of div

### ISSUE THREAD

**Issue by Lenibi** [imd1005-web-development-winter-2023/assignment-03-Lenibi#2]
```
.button1{
  width: 100%;
  place-self: center stretch;
  background-color: #e63946;
}
```

line 57 in style.css
![image](https://user-images.githubusercontent.com/121530588/226142748-ee0a2e68-ecdc-40d6-ab3d-232bc410f77b.png)

I want the buttons to fill up the entire area, I tried height 100% and it did not work

**Comment by neilmispelaar** [comment]
Awesome sauce. Well done sorting out your issue and also closing it! 🚢
