### ISSUE TITLE
Page Link not updating (css not working)

### ISSUE THREAD

**Issue by Lenibi** [imd1005-web-development-winter-2023/assignment-03-Lenibi#3]
I commited changed by copy pasting code in the index css and javascript files and added a picture and font file, but it still looks like the old design
![image](https://user-images.githubusercontent.com/121530588/226148044-e89fdd72-0216-4231-880d-0acdcd0b5206.png)

should look like this:
![image](https://user-images.githubusercontent.com/121530588/226148053-ad9ad095-8fb9-4a05-b75b-0aac5bc70c83.png)

this is the pages link
https://imd1005-web-development-winter-2023.github.io/assignment-03-Lenibi/

the css code does seem to be updated but doesnt show on the new website

**Comment by neilmispelaar** [comment]
It’s likely you have to do CTRL+F5 to clear your browser cache. 

Here’s what it looks like on my phone right now: 

![0D19D29B-AE15-484A-B30B-791FB914CA39](https://user-images.githubusercontent.com/9325038/226148233-2ac54391-d147-4ee3-9f5b-9f8c43a170fa.png)

**Comment by Lenibi** [comment]
Yeah it works now thank you
