### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by Lenibi** [imd1005-web-development-winter-2023/assignment-03-Lenibi#4]
![image](https://user-images.githubusercontent.com/121530588/226148170-b7ff42f6-bf7a-4153-9ff9-0835f5fbd50c.png)
When I shrink the page horizontally, the text resizes fine but the top row (the dark blue rectangle) stays the same size.
`.quadrants{
  height: 100%;
  display: grid;
  grid-template-columns: 300px 1fr;
  grid-template-rows: 100px 1fr;
}`
line 73 css

 I tried doing `grid-template-rows: 10%1fr;`  but it did not work

How would I make the first row resize to fit the text?

**Comment by neilmispelaar** [comment]
I would recommend looking into media queries (we have some notes and code samples in the imd1005.ca site and previous exercises) 

Also, don’t use fixed pixel sizes for rows or column heights / widths as then they won’t resize if the content spills out of the area available.

**Comment by neilmispelaar** [comment]
You could also change the page structure so that the top row is in a `header` and then deal with the header resizing and `main` area resizing separately.

**Comment by Lenibi** [comment]
Thanks
The fix was really simple I just changed it to `grid-template-rows: 0.1fr 1fr;`
