### ISSUE TITLE
Classlist add not working

### ISSUE THREAD

**Issue by Lenibi** [imd1005-web-development-winter-2023/assignment-03-Lenibi#5]
![image](https://user-images.githubusercontent.com/121530588/226151594-e17743e1-da68-4586-a60b-fddb0c2fda82.png)
`timerText.classList.add("redText");`
is not working and i get an error
![image](https://user-images.githubusercontent.com/121530588/226151605-079fb61a-c01b-4013-8535-db68df64dc77.png)
the keydown function works

the classList also does not autocomplete

**Comment by neilmispelaar** [comment]
You’re using getElementsByClassname() to get the timerText 

https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementsByClassName

Note that that method returns an array of nodes (getElementS plural). 

And there is no classList property on an array of elements.

**Comment by neilmispelaar** [comment]
If you see errors like cannot read property undefined use console.log(timerText) to check that the object or value isn’t null or some other unexpected thing.

**Comment by Lenibi** [comment]
![image](https://user-images.githubusercontent.com/121530588/226151808-582c5dc3-4881-404f-ab65-da3052c9d4bf.png)
It works now thanks
youre right it returns an array
